flaskr/models/__init__.py
#coding:utf-8
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

# 初始化模型
def init_app(app):
    db.init_app(app)
    return db

flaskr/models/account.py
#coding:utf-8
# 账户模型

from . import db

class Account(db.Model):
    __tablename__ = 'tb_account'
    nickname = db.Column(db.String(255), doc="昵称", nullable=True)
    openid = db.Column(db.String(255), doc="openid",  primary_key=True)
    session_key = db.Column(db.String(255), doc="session_key", nullable=True)
    is_admin = db.Column(db.String(255), doc="账户角色", nullable=True)
    avatar = db.Column(db.String(255), doc="头像", nullable=True)
    finish_time = db.Column(db.String(255), doc="完成答卷时间")
    regist_time = db.Column(db.String(255), doc="注册时间", nullable=True)
    
    def to_json(self):
        return {
            'nickname': self.nickname,
            'openid': self.openid,
            'session_key': self.session_key,
            'is_admin': self.is_admin,
            'avatar': self.avatar,
            'finish_time': self.finish_time,
            'regist_time': self.regist_time
        }
        
class BaseInfo(db.Model):
    __tablename__ = 'tb_baseInfo'
    openid = db.Column(db.String(255), doc='openid', primary_key=True)
    name = db.Column(db.String(255), doc='', nullable=True)
    date = db.Column(db.String(255), doc='', nullable=True)
    culture = db.Column(db.String(255), doc='', nullable=True)
    erMing = db.Column(db.String(255), doc='', nullable=True)
    during = db.Column(db.String(255), doc='', nullable=True)
    keeping = db.Column(db.String(255), doc='', nullable=True)
    env = db.Column(db.String(255), doc='', nullable=True)
    voice = db.Column(db.String(255), doc='', nullable=True)
    feel = db.Column(db.String(255), doc='', nullable=True)
    
    def to_json(self):
        return {
            'openid': self.openid,
            'name': self.name,
            'date': self.date,
            'culture': self.culture,
            'erMing': self.erMing,
            'during': self.during,
            'keeping': self.keeping,
            'env': self.env,
            'voice': self.voice,
            'feel': self.feel
        }
        
class Record(db.Model):
    __tablename__ = 'tb_record'
    openid = db.Column(db.String(255), doc="账户id", primary_key=True)
    finish_time = db.Column(db.String(255), doc="完成答卷时间")
    score_1 = db.Column(db.String(255), doc="")
    score_2_1 = db.Column(db.String(255), doc="")
    score_2_2 = db.Column(db.String(255), doc="")
    score_2_3 = db.Column(db.String(255), doc="")
    score_3 = db.Column(db.String(255), doc="")
    score_4_1 = db.Column(db.String(255), doc="")
    score_4_2 = db.Column(db.String(255), doc="")
    score_4_3 = db.Column(db.String(255), doc="")
    score_4_4 = db.Column(db.String(255), doc="")
    score_4_5 = db.Column(db.String(255), doc="")
    
    def to_json(self):
        return {
            'openid': self.openid,
            'finish_time': self.finish_time,
            'score_1': self.score_1,
            'score_2_1': self.score_2_1,
            'score_2_2': self.score_2_2,
            'score_2_3': self.score_2_3,
            'score_3': self.score_3,
            'score_4_1': self.score_4_1,
            'score_4_2': self.score_4_2,
            'score_4_3': self.score_4_3,
            'score_4_4': self.score_4_4,
            'score_4_5': self.score_4_5
        }
    

flaskr/routes/__init__.py
from .account import account_bp

def init_app(app):
    app.register_blueprint(account_bp)

flaskr/routes/account.py
#coding:utf-8
# 认证（登录/注册）路由

from flask import Blueprint, request, render_template, url_for, redirect, send_file
from sqlalchemy.sql import base
from xlsxwriter import Workbook
from models.account import Account, BaseInfo, Record  # 账户模型
from models import db
import time
import io

from flask import Blueprint

account_bp = Blueprint('account', __name__, url_prefix='')


@account_bp.route('/', methods=['GET'])
def getUserInfo():
    data = []
    try:
        account_list = db.session.query(Account).filter(Account.finish_time.isnot(None)).all()
        for account in account_list:
            account = account.to_json()
            account['baseInfo'] = db.session.query(BaseInfo).filter(account['openid'] == BaseInfo.openid).first().to_json()
            account['record'] = db.session.query(Record).filter(account['openid'] == Record.openid).first().to_json()
            data.append(account)
        result = {
            'data': data,
            'sum': len(data)
        }
        return render_template('index.html', result=result) 
    except Exception as e:
        error = f'用户列表错误:{e}'
        return render_template('error.html', result=error) 
        


@account_bp.route('/remove', methods=['POST'])
def post_info():
    try:
        req = request.form
        if 'openid' not in req:
            raise Exception('缺少openid参数')
        openid = req['openid']
        # 方式1: 先查后删除
        record = db.session.query(Record).filter(Record.openid == openid).first()
        baseInfo = db.session.query(BaseInfo).filter(BaseInfo.openid == openid).first()
        account = db.session.query(Account).filter(Account.openid == openid).first()
        if record and baseInfo and account:
            # 删除数据
            db.session.delete(record)
            db.session.commit()
            time.sleep(0.5)
            db.session.delete(baseInfo)
            db.session.commit()
            time.sleep(0.5)
            db.session.delete(account)
            # 提交会话 增删改都要提交会话
            db.session.commit()
        else:
            raise Exception('数据删除失败，未查找到对应信息')
        return redirect(url_for('account.getUserInfo'))
    except Exception as e:
        error = f'删除信息错误:{e}'
        return render_template('error.html', result=error) 

@account_bp.route('/excel', methods=['GET'])
# 导出数据为excel
def get_excel():
    try:
        fp=create_workbook() 
        fp.seek(0)
        return send_file(fp,attachment_filename='调查结果.xlsx',as_attachment=True)
    except Exception as e:
        error = f'导出数据错误:{e}'
        return render_template('error.html', result=error) 
        
def create_workbook():    
    fp=io.BytesIO()
    book=Workbook(fp)
    sheet=book.add_worksheet('数据集合1')

    account_list = db.session.query(Account).filter(Account.finish_time.isnot(None)).all()
    i = 0
    # sheet.write(i, 0, ['昵称', '姓名', '出生日期', '教育背景', '', '完成时间', '注册时间'])
    for account in account_list:
        account = account.to_json()
        baseInfo = db.session.query(BaseInfo).filter(account['openid'] == BaseInfo.openid).first().to_json()
        record = db.session.query(Record).filter(account['openid'] == Record.openid).first().to_json()
        account = list(account.values())
        baseInfo = list(baseInfo.values())
        record = list(record.values())
        
        print(account)
        print(baseInfo)
        print(record)
        values = []
        
        # sheet.write(i, 1, account['nickname'])
        i += 1
    book.close()
    return fp

flaskr/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>错误页面</title>
</head>
<body>
    <div class="container" style="margin: 2rem auto;">
        <div>错误信息:</div>
        <div style="font-weight: 700;">{{ result }}</div>
        <div><a href="{{ url_for('account.getUserInfo') }}">返回首页</a></div>
    </div>
</body>
</html>

flaskr/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>管理后台</title>
</head>

<body>
    <div class="container" style="padding: 5rem 0;">
        <p class="h2">信息管理后台</p>
        <!-- <form action="{{ url_for('account.get_excel') }}" method="get" style="margin: 1rem 0;"></form> -->
        <form action="" method="get" style="margin: 1rem 0;">
            <span>完成问卷数据总量： {{ result.sum }}</span>
            <button type="submit" class="btn btn-success" style="float: right; margin-right: 5rem;">导出数据</button>
        </form>
        <table class="table table-striped table-hover">
            <thead>
                <th width="50px">昵称</th>
                <th>姓名</th>
                <th width="100px">出生日期</th>
                <th width="100px">学历</th>
                <th>完成时间</th>
                <th>注册时间</th>
                <th width="150px">删除操作</th>
            </thead>
            <tbody>
                {% for item in result.data %}
                <tr>
                    <td>{{ item.nickname }}</td>
                    <td>{{ item.baseInfo.name }}</td>
                    <td>{{ item.baseInfo.date }}</td>
                    <td>{{ item.baseInfo.culture }}</td>
                    <td>{{ item.finish_time }}</td>
                    <td>{{ item.regist_time }}</td>
                    <td>
                        <form action="{{ url_for('account.post_info') }}" method="POST">
                            <button type="submit" class="btn btn-danger" name="openid"
                                value="{{ item.openid }}">删除</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>

</html>

<script>
    function exportExcel(result) {
        console.log(result)
    }
</script>